# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteDialog(object):
    def setupUi(self, deleteDialog):
        deleteDialog.setObjectName("deleteDialog")
        deleteDialog.resize(304, 68)
        icon = QtGui.QIcon.fromTheme("password")
        deleteDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(deleteDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.dialogButtons = QtWidgets.QDialogButtonBox(deleteDialog)
        self.dialogButtons.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dialogButtons.setOrientation(QtCore.Qt.Horizontal)
        self.dialogButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialogButtons.setObjectName("dialogButtons")
        self.gridLayout.addWidget(self.dialogButtons, 1, 0, 1, 1)
        self.warningLabel = QtWidgets.QLabel(deleteDialog)
        self.warningLabel.setText("")
        self.warningLabel.setObjectName("warningLabel")
        self.gridLayout.addWidget(self.warningLabel, 0, 0, 1, 1)

        self.retranslateUi(deleteDialog)
        self.dialogButtons.accepted.connect(deleteDialog.accept)
        self.dialogButtons.rejected.connect(deleteDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(deleteDialog)

    def retranslateUi(self, deleteDialog):
        _translate = QtCore.QCoreApplication.translate
        deleteDialog.setWindowTitle(_translate("deleteDialog", "PassMan - Delete entry?"))
