# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setmasterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setmasterDialog(object):
    def setupUi(self, setmasterDialog):
        setmasterDialog.setObjectName("setmasterDialog")
        setmasterDialog.resize(570, 199)
        icon = QtGui.QIcon.fromTheme("password")
        setmasterDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(setmasterDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.confirmField = QtWidgets.QLineEdit(setmasterDialog)
        self.confirmField.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.confirmField.setClearButtonEnabled(True)
        self.confirmField.setObjectName("confirmField")
        self.gridLayout.addWidget(self.confirmField, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(setmasterDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.masterkeyField = QtWidgets.QLineEdit(setmasterDialog)
        self.masterkeyField.setStatusTip("")
        self.masterkeyField.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.masterkeyField.setClearButtonEnabled(True)
        self.masterkeyField.setObjectName("masterkeyField")
        self.gridLayout.addWidget(self.masterkeyField, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(setmasterDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.toggleMasterkey = QtWidgets.QToolButton(setmasterDialog)
        self.toggleMasterkey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleMasterkey.setText("")
        self.toggleMasterkey.setCheckable(True)
        self.toggleMasterkey.setObjectName("toggleMasterkey")
        self.gridLayout.addWidget(self.toggleMasterkey, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(setmasterDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.toggleConfirm = QtWidgets.QToolButton(setmasterDialog)
        self.toggleConfirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleConfirm.setText("")
        self.toggleConfirm.setCheckable(True)
        self.toggleConfirm.setObjectName("toggleConfirm")
        self.gridLayout.addWidget(self.toggleConfirm, 2, 2, 1, 1)
        self.dialogButtons = QtWidgets.QDialogButtonBox(setmasterDialog)
        self.dialogButtons.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dialogButtons.setOrientation(QtCore.Qt.Horizontal)
        self.dialogButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialogButtons.setObjectName("dialogButtons")
        self.gridLayout.addWidget(self.dialogButtons, 3, 0, 1, 3)

        self.retranslateUi(setmasterDialog)
        self.dialogButtons.accepted.connect(setmasterDialog.accept)
        self.dialogButtons.rejected.connect(setmasterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(setmasterDialog)
        setmasterDialog.setTabOrder(self.masterkeyField, self.toggleMasterkey)
        setmasterDialog.setTabOrder(self.toggleMasterkey, self.confirmField)
        setmasterDialog.setTabOrder(self.confirmField, self.toggleConfirm)

    def retranslateUi(self, setmasterDialog):
        _translate = QtCore.QCoreApplication.translate
        setmasterDialog.setWindowTitle(_translate("setmasterDialog", "PassMan - Set master key"))
        self.confirmField.setToolTip(_translate("setmasterDialog", "Confirm your master key/password"))
        self.confirmField.setPlaceholderText(_translate("setmasterDialog", "Confirm your master key/password"))
        self.label_3.setText(_translate("setmasterDialog", "Confirm master key:"))
        self.masterkeyField.setToolTip(_translate("setmasterDialog", "Enter your master key/password"))
        self.masterkeyField.setPlaceholderText(_translate("setmasterDialog", "Enter your master key/password"))
        self.label_2.setText(_translate("setmasterDialog", "Master key:"))
        self.toggleMasterkey.setToolTip(_translate("setmasterDialog", "Toggle password visibility"))
        self.label.setText(_translate("setmasterDialog", "Hello, welcome to PassMan, a simple password manager. It looks like this is your first time starting PassMan, please set a master key/password below (It it recommended to use a strong master key with a minimum length of 8 characters and a combination of uppercase letters, lowercase letters, numbers and other symbols):"))
        self.toggleConfirm.setToolTip(_translate("setmasterDialog", "Toggle password visibility"))
